---
name: trainsolo
description: A new Flutter application.
publish_to: none
version: 1.0.2+102
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^0.2.3
  page_indicator: ^0.4.1
  syncfusion_flutter_sliders: ^19.1.66-beta
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  form_field_validator: ^1.1.0
  rxdart: ^0.24.1
  flutter_bloc: ^7.0.1
  http: ^0.12.1
  progress_dialog: ^1.2.4
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  toast: ^0.1.5
  flutter_dash: ^0.0.1
  vimeoplayer: ^0.1.8
  flutter_inappwebview: ^3.4.0+2
  async: ^2.4.0
  positioned_tap_detector: ^1.0.3
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.0.0
  syncfusion_flutter_core: ^19.2.44+1
  share: ^0.6.5+4
  fluttertoast: ^8.0.7
  percent_indicator: "^2.1.7+2"
  flutter_pagewise: ^2.0.1
  scroll_indicator: ^0.0.3
  charts_flutter: ^0.11.0
  firebase_dynamic_links: ^2.0.7
  firebase_core: ^1.7.0
  readmore: ^2.1.0
  image_picker: ^0.6.5+3
  purchases_flutter: ^3.4.5
  uuid: 2.0.0
  url_launcher: 6.0.4
  #  firebase_analytics: 7.1.1
  amplitude_flutter: ^3.2.1
  circular_countdown_timer: ^0.2.0
  get_version: ^0.2.2
#dependency_overrides:
#  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/subs1.png
    - assets/subs2.png
    - assets/trainsolo.png
    - assets/splash.png
    - assets/logowhite.png
    - assets/football.png
    - assets/splashlog.png
    - assets/listimage.png
    - assets/playerpic.jpg
    - assets/firstcrown.png
    - assets/profileboy.png
    - assets/profilegirl.png
    - assets/profileboynew.png
    - assets/footballground.png
    - assets/t_shirt_blank.png
    - assets/t_shirt_red.png
    - assets/graphimage.png
    - assets/yellow_star.png
    - assets/medal_first.png
    - assets/medal_second.png
    - assets/medal_thired.png
    - assets/ball_work.png
    - assets/juggling.png
    - assets/wall_work.png
    - assets/red_ball.png
    - assets/missionimmage.png
    - assets/college_campus.jpeg


  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 700
    - family: HelveticaNeue
      fonts:
        - asset: fonts/helveticaneue-medium.ttf
    - family: TrainsoloIcons
      fonts:
        - asset: assets/TrainsoloIcons.ttf
