/// Flutter icons TrainsoloIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TrainsoloIcons
///      fonts:
///       - asset: fonts/TrainsoloIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TrainsoloIcons {
  TrainsoloIcons._();

  static const _kFontFam = 'TrainsoloIcons';
  static const String _kFontPkg = null;

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData other = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passing = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_white = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_arrow_red = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle_outline_white = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData player1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_bin = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_right = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_next_white_right = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_previous_white_left = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_soccer_black = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_soccer_red = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_soccer_red_small = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_rating_3d = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt_blank = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt_red = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ts_logo = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_settings_white = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_white = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wall_walk = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ball_mastery = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_black_24dp_1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_remove_white = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_white = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_red_sqare = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_white_circle = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle_green = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cm_red_round = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coach = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collage = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbling = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drill_record = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border_white_24dp_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData green_check = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_248 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_border = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highschool = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData juggling = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mission = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shooting = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
